-- DEPRECATED
-- Do not execute this legacy RPC file.
--
-- The hardened merge_sku() definition now lives in:
--   supabase_migration_rpc_hardened.sql
--
-- The hardened version removes the front-end supplied p_user argument and gets
-- the operator from auth.uid() -> public.user_profiles.
