-- DEPRECATED
-- Do not execute this legacy RPC file.
--
-- The hardened confirm_order() definition now lives in:
--   supabase_migration_rpc_hardened.sql
--
-- That migration keeps the atomic stock update behavior and adds database-side
-- role checks through auth.uid() -> public.user_profiles via current_user_role().
