-- DEPRECATED
-- Do not use this legacy plaintext-password users table.
--
-- GMpos now uses Supabase Auth plus public.user_profiles.
-- Execute supabase_migration_user_profiles.sql and create users through
-- Supabase Dashboard > Authentication instead.
